In [1]:
# HIDDEN
# Altera caminho para manter padrão com Jupyter Book
%cd chapters/05/05/

/home/danielavancini/Projects/eng-analytics/chapters/05/05

# 5.5 Lógica condicional com  CASE WHEN

Além das consultas simples e funções agregadas,  o SQL também permite a utilização de lógicas condicionais avançadas através da sintaxe `CASE WHEN`. Leitores usuários de planilhas eletrônicas logo notarão a semelhança com a função `IF ELSE()` e suas derivações.

O `CASE WHEN` é uma operação realizada em cima dos valores de uma ou mais colunas que retorna uma nova coluna com o resultado da condição:

```sql
SELECT
  CASE
    WHEN condicao1 THEN resultado1
    WHEN condicao2 THEN resultado2
    (...)
    ELSE resultado_se_falso
  END AS nome_nova_coluna
FROM tabela
GROUP BY <nome_do_campo1,nome_do_campo2, etc..>
```

No exemplo abaixo, classificamos os produtos da Northwind em diferentes categorias de preço usando o CASE WHEN:

In [2]:
# HIDDEN
# Vamos utilizar a extensão ipython-sql junto com o pacote SQLAlchemy para rodar consultas SQL diretamente
from sqlalchemy import create_engine
path_data = '../../assets/data/'
%load_ext sql
%config SqlMagic.displaycon=False
%config SqlMagic.feedback=False

# Agora dizemos para a extensão do ipython-sql onde estão os dados
%sql sqlite:///../../../assets/data/northwind.sqlite

In [3]:
%%sql
SELECT ProductName, UnitPrice,
 CASE
   WHEN UnitPrice >= 100 THEN "Alto Valor"
   WHEN UnitPrice > 50 and "UnitPrice" < 100 THEN "Médio Valor"
   ELSE "Baixo Valor"
 END AS ProductCategory
FROM 'Product'
LIMIT 10

[('Chai', 18, 'Baixo Valor'),
 ('Chang', 19, 'Baixo Valor'),
 ('Aniseed Syrup', 10, 'Baixo Valor'),
 ("Chef Anton's Cajun Seasoning", 22, 'Baixo Valor'),
 ("Chef Anton's Gumbo Mix", 21.35, 'Baixo Valor'),
 ("Grandma's Boysenberry Spread", 25, 'Baixo Valor'),
 ("Uncle Bob's Organic Dried Pears", 30, 'Baixo Valor'),
 ('Northwoods Cranberry Sauce', 40, 'Baixo Valor'),
 ('Mishi Kobe Niku', 97, 'Médio Valor'),
 ('Ikura', 31, 'Baixo Valor'),
 ('Queso Cabrales', 21, 'Baixo Valor'),
 ('Queso Manchego La Pastora', 38, 'Baixo Valor'),
 ('Konbu', 6, 'Baixo Valor'),
 ('Tofu', 23.25, 'Baixo Valor'),
 ('Genen Shouyu', 15.5, 'Baixo Valor'),
 ('Pavlova', 17.45, 'Baixo Valor'),
 ('Alice Mutton', 39, 'Baixo Valor'),
 ('Carnarvon Tigers', 62.5, 'Médio Valor'),
 ('Teatime Chocolate Biscuits', 9.2, 'Baixo Valor'),
 ("Sir Rodney's Marmalade", 81, 'Médio Valor'),
 ("Sir Rodney's Scones", 10, 'Baixo Valor'),
 ("Gustaf's Knäckebröd", 21, 'Baixo Valor'),
 ('Tunnbröd', 9, 'Baixo Valor'),
 ('Guaraná Fantástica', 4.5, 'Baixo Valor'),
 ('NuNuCa Nuß-Nougat-Creme', 14, 'Baixo Valor'),
 ('Gumbär Gummibärchen', 31.23, 'Baixo Valor'),
 ('Schoggi Schokolade', 43.9, 'Baixo Valor'),
 ('Rössle Sauerkraut', 45.6, 'Baixo Valor'),
 ('Thüringer Rostbratwurst', 123.79, 'Alto Valor'),
 ('Nord-Ost Matjeshering', 25.89, 'Baixo Valor'),
 ('Gorgonzola Telino', 12.5, 'Baixo Valor'),
 ('Mascarpone Fabioli', 32, 'Baixo Valor'),
 ('Geitost', 2.5, 'Baixo Valor'),
 ('Sasquatch Ale', 14, 'Baixo Valor'),
 ('Steeleye Stout', 18, 'Baixo Valor'),
 ('Inlagd Sill', 19, 'Baixo Valor'),
 ('Gravad lax', 26, 'Baixo Valor'),
 ('Côte de Blaye', 263.5, 'Alto Valor'),
 ('Chartreuse verte', 18, 'Baixo Valor'),
 ('Boston Crab Meat', 18.4, 'Baixo Valor'),
 ("Jack's New England Clam Chowder", 9.65, 'Baixo Valor'),
 ('Singaporean Hokkien Fried Mee', 14, 'Baixo Valor'),
 ('Ipoh Coffee', 46, 'Baixo Valor'),
 ('Gula Malacca', 19.45, 'Baixo Valor'),
 ('Rogede sild', 9.5, 'Baixo Valor'),
 ('Spegesild', 12, 'Baixo Valor'),
 ('Zaanse koeken', 9.5, 'Baixo Valor'),
 ('Chocolade', 12.75, 'Baixo Valor'),
 ('Maxilaku', 20, 'Baixo Valor'),
 ('Valkoinen suklaa', 16.25, 'Baixo Valor'),
 ('Manjimup Dried Apples', 53, 'Médio Valor'),
 ('Filo Mix', 7, 'Baixo Valor'),
 ('Perth Pasties', 32.8, 'Baixo Valor'),
 ('Tourtière', 7.45, 'Baixo Valor'),
 ('Pâté chinois', 24, 'Baixo Valor'),
 ('Gnocchi di nonna Alice', 38, 'Baixo Valor'),
 ('Ravioli Angelo', 19.5, 'Baixo Valor'),
 ('Escargots de Bourgogne', 13.25, 'Baixo Valor'),
 ('Raclette Courdavault', 55, 'Médio Valor'),
 ('Camembert Pierrot', 34, 'Baixo Valor'),
 ("Sirop d'érable", 28.5, 'Baixo Valor'),
 ('Tarte au sucre', 49.3, 'Baixo Valor'),
 ('Vegie-spread', 43.9, 'Baixo Valor'),
 ('Wimmers gute Semmelknödel', 33.25, 'Baixo Valor'),
 ('Louisiana Fiery Hot Pepper Sauce', 21.05, 'Baixo Valor'),
 ('Louisiana Hot Spiced Okra', 17, 'Baixo Valor'),
 ('Laughing Lumberjack Lager', 14, 'Baixo Valor'),
 ('Scottish Longbreads', 12.5, 'Baixo Valor'),
 ('Gudbrandsdalsost', 36, 'Baixo Valor'),
 ('Outback Lager', 15, 'Baixo Valor'),
 ('Flotemysost', 21.5, 'Baixo Valor'),
 ('Mozzarella di Giovanni', 34.8, 'Baixo Valor'),
 ('Röd Kaviar', 15, 'Baixo Valor'),
 ('Longlife Tofu', 10, 'Baixo Valor'),
 ('Rhönbräu Klosterbier', 7.75, 'Baixo Valor'),
 ('Lakkalikööri', 18, 'Baixo Valor'),
 ('Original Frankfurter grüne Soße', 13, 'Baixo Valor')]

Mas o que aconteceria se ao invés de simplesmente classificar os produtos nessa nova categoria, quiséssemos contar quantos produtos estão em cada uma? Para isso, basta aplicar  uma consulta agregada `COUNT` utilizando nossa nova coluna como parte da cláusula `GROUP BY`:

In [5]:
%%sql

SELECT COUNT(ProductName) as num_produtos,
 CASE
   WHEN UnitPrice >= 100 THEN "Alto Valor"
   WHEN UnitPrice > 50 and "UnitPrice" < 100 THEN "Médio Valor"
   ELSE "Baixo Valor"
 END AS ProductCategory
FROM 'Product'
GROUP BY ProductCategory

[(2, 'Alto Valor'), (70, 'Baixo Valor'), (5, 'Médio Valor')]

Agora que criamos nossa categorização de produtos, podemos dar um passo a mais e usá-la para calcular nossas vendas totais por categoria. Mas como fazemos isso se essa coluna só existe em nossa consulta SQL e não no banco de dados em si? Para isso vamos utilizar o conceito da subquery (ou subconsulta). Até a proxima seção!